In [412]:
import pandas as pd
import numpy as np

In [413]:
#Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data. (2.5 points)
fb = pd.read_csv('Laliga.csv')
fb.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1

In [414]:
#Rearrange dataframe with proper column name
fb  = pd.DataFrame(fb.values[1:], columns=fb.iloc[0])
fb.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

In [415]:
#replace dashes with 0 to make sure you can perform arithmetic operations on the data. (2.5 points)
fb = fb.replace(to_replace="-", value="0")

In [416]:
#Print all the teams which have started playing between 1930-1980. (5 points)
print('Teams that started playing between 1930-1980:')
fb[(fb['Debut'] >= '1930') & (fb['Debut'] <= '1980')]['Team']

Teams that started playing between 1930-1980:

3                Valencia
5                 Sevilla
8                Zaragoza
9              Real Betis
10    Deportivo La Coruna
11             Celta Vigo
12             Valladolid
14         Sporting Gijon
15                Osasuna
16                 Malaga
17                 Oviedo
18               Mallorca
19             Las Palmas
21                Granada
22         Rayo Vallecano
23                  Elche
25               Hercules
26               Tenerife
27                 Murcia
28                 Alaves
29                Levante
30              Salamanca
31               Sabadell
32                  Cadiz
34              Castellon
37                Cordoba
39             Recreativo
40              Burgos CF
41             Pontevedra
46              Gimnastic
49               Alcoyano
50                   Jaen
52             AD Almeria
54                 Lleida
57                 Condal
58        Atletico Tetuan
59       Cultural Leonesa
Name: Team, dtype: object

In [417]:
#Print the list of teams which came Top 5 in terms of points (2.5 points)
fb['Points']=pd.to_numeric(fb['Points'])
print('Top 5 Teams in terms of Points')
fb.nlargest(5, 'Points')['Team']

Top 5 Teams in terms of Points

0        Real Madrid
1          Barcelona
2    Atletico Madrid
3           Valencia
4    Athletic Bilbao
Name: Team, dtype: object

In [418]:
###Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. 
###Using the same function, find the team which has maximum and minimum goal difference. (5 points)
###*Goal_diff_count = GoalsFor - GoalsAgainst

def Goal_diff_count(GoalsFor, GoalsAgainst):
    return abs(GoalsFor - GoalsAgainst)

fb['GamesPlayed']=pd.to_numeric(fb['GamesPlayed'])
fb['GoalsFor']=pd.to_numeric(fb['GoalsFor'])
fb['GoalsAgainst']=pd.to_numeric(fb['GoalsAgainst'])

fb['GoalsDiffCount']=Goal_diff_count(fb['GoalsFor'], fb['GoalsAgainst'])
print('Minimum goal diff count team:\n', fb.nsmallest(1,'GoalsDiffCount')['Team'])
print('\n\nMaximum goal diff count team:\n', fb.nlargest(1,'GoalsDiffCount')['Team'])

Minimum goal diff count team:
 60    Girona
Name: Team, dtype: object


Maximum goal diff count team:
 0    Real Madrid
Name: Team, dtype: object

In [419]:
###*5. Create a new column with name “Winning Percent” and append it to the data set (5 points)
###*Percentage of Winning = (GamesWon / GamesPlayed)*100
###*If there are any numerical error, replace it with 0%
###*Print the top 5 teams which has the highest Winning percentage

fb['GamesWon']=pd.to_numeric(fb['GamesWon'])
fb['GamesPlayed']=pd.to_numeric(fb['GamesPlayed'])

fb['Winning Percent']=(fb['GamesWon']/fb['GamesPlayed'])*100

print('Top 5 Winning percentage Teams:\n', fb.nlargest(5,'GoalsDiffCount')['Team'])

Top 5 Winning percentage Teams:
 0        Real Madrid
1          Barcelona
2    Atletico Madrid
4    Athletic Bilbao
3           Valencia
Name: Team, dtype: object

In [420]:
###*6. Group teams based on their “Best position” and print the sum of their points for all positions (5 points)

###*Eg: Best Position     Points

###*         1                   25000

###*         2                    7000
fb['BestPosition']=pd.to_numeric(fb['BestPosition'])
db = fb.groupby(['BestPosition'], as_index=True).agg({'Points':sum})
print(db)

              Points
BestPosition
1              27933
2               6904
3               5221
4               6563
5               1884
6               2113
7               1186
8               1134
9                 96
10               450
11               445
12               511
14                71
15                14
16                81
17               266
19                81
20                34